import { GameEngine } from "./GameEngine/Core/GameEngine";
import { ImageBackground } from "./GameEngine/Core/ImageBackground";
import { GameManagerObject } from "./Mario/GameObjects/GameManagerObject";
import { Player } from "./Mario/GameObjects/Player";
import { Ball } from "./Mario/GameObjects/Ball";
import { Computer } from "./Mario/GameObjects/Computer";
import Background from "./assets/images/background.png";
import { Trump } from "./Mario/GameObjects/Trump";
import { RenderingEngine } from "./GameEngine/Core/RenderingEngine";
import { Ground } from "./Mario/GameObjects/Ground";
import { Color } from "./GameEngine/Core/Enums/Color";
let gameCanvas = document.getElementById("game-canvas");
let gameEngine = GameEngine.buildGameEngine(gameCanvas);
RenderingEngine.instance.renderGizmos = true;
let background = new ImageBackground(gameCanvas, Background);
let gameManager = new GameManagerObject("GameManager");
let player = new Player("player");
let ball = new Ball("ball");
let computer = new Computer("computer");
let trump = new Trump("trump");
let ground = new Ground(350, 400, 700, 55, Color.Brown);
let ground2 = new Ground(400, 270, 100, 10, Color.Brown);
let gameObjects = [gameManager, player, computer, ball, trump, ground, ground2];
gameEngine.initializeGame(gameObjects, background);
gameEngine.startGame();
//# sourceMappingURL=index.js.map