# This workflow is triggered manually using workflow_dispatch
#
# Secrets used:
# NPM_TOKEN: access token for NPM. Obtained on NPM site.

name: Manual Publish

on:
  workflow_dispatch:
    inputs:
      confirm:
        description: Confirm
        required: true
      git-ref:
        description: Git Ref (Optional)
        required: false

jobs:
  check_response:
    runs-on: ubuntu-latest
    name: Check Response
    steps:
      - name: Check Response
        run: |
          response=${{ github.event.inputs.confirm }}
          if [ ${response^^} != 'YES' ]
          then
            exit 1 
          fi

  publish_packages:
    runs-on: ubuntu-latest
    name: Publish Packages
    needs:
      - check_response
    steps:
      - name: Checkout
        if: github.event.inputs.git-ref == ''
        uses: actions/checkout@v2
      - name: Checkout (Custom Ref)
        if: github.event.inputs.git-ref != ''
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.inputs.git-ref }}
      - uses: actions/setup-node@v1
        with:
          node-version: "12"
      - uses: actions/cache@v2
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-
      - name: Install dependencies
        run: npm install
      - name: Build packages
        run: npm run compile
      - name: Authenticate with GitHub
        run: |
          # git config http.https://github.com/.extraheader "AUTHORIZATION: basic $(echo x-access-token:${{secrets.GITHUB_TOKEN}} | base64)"
          git remote set-url origin https://x-access-token:${{secrets.GITHUB_TOKEN}}@github.com/${GITHUB_REPOSITORY}.git
          git checkout $BRANCH
          git config user.name "Github Actions"
          git config user.email "bot@github.com"
      - name: Stash changes
        run: git stash
      - name: Authenticate with NPM
        run: |
          echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" >> .npmrc
          npm whoami
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
      - name: Publish
        run: npx lerna publish --yes
        env:
          GH_TOKEN: ${{secrets.GITHUB_TOKEN}}
