import type { ISerializedGameObject } from '@entropy-engine/entropy-game-engine';
import type { IEditorPrefab } from '../../shared/types';

/**
 * Generate the prefabs.json manifest — an array of ISerializedGameObject templates
 * keyed by prefab name. This is loaded at runtime by the engine's PrefabRegistry.
 *
 * Throws if prefab names are not unique.
 */
export function generatePrefabManifest(prefabs: IEditorPrefab[]): ISerializedGameObject[] {
  validateUniquePrefabNames(prefabs);
  return prefabs.map(prefab => structuredClone(prefab.template));
}

/**
 * Generate the prefabs.d.ts declaration file content for type-safe prefab names.
 * Uses declaration merging to narrow PrefabName in the engine module.
 */
export function generatePrefabTypeDeclaration(prefabs: IEditorPrefab[]): string {
  if (prefabs.length === 0) {
    return [
      '// Auto-generated by Entropy Editor — do not edit manually',
      '',
      "declare module '@entropy-engine/entropy-game-engine' {",
      '  export type PrefabName = never;',
      '}',
      ''
    ].join('\n');
  }

  const unionMembers = prefabs
    .map(p => `  | '${p.name.replace(/'/g, "\\'")}'`)
    .join('\n');

  return [
    '// Auto-generated by Entropy Editor — do not edit manually',
    '',
    "declare module '@entropy-engine/entropy-game-engine' {",
    `  export type PrefabName =\n${unionMembers};`,
    '}',
    ''
  ].join('\n');
}

/**
 * Validate that all prefab names are unique.
 * The engine's PrefabRegistry uses template.name as the key, so duplicates would silently overwrite.
 */
function validateUniquePrefabNames(prefabs: IEditorPrefab[]): void {
  const seen = new Set<string>();

  for (const prefab of prefabs) {
    if (seen.has(prefab.name)) {
      throw new Error(`Duplicate prefab name: "${prefab.name}". Prefab names must be unique for export.`);
    }

    seen.add(prefab.name);
  }
}
